### ISSUE TITLE
Possible problems detected using eslint

### ISSUE THREAD

**Issue by MadMG** [Mik13/npm-kraken-api#12]
eslint output

`\npm-kraken-api>eslint kraken.js`

> \npm-kraken-api\kraken.js
>   156:28  error  'self' is not defined  no-undef
>   169:28  error  'self' is not defined  no-undef
>   192:29  error  'self' is not defined  no-undef
>   201:29  error  'self' is not defined  no-undef
>   210:21  error  'self' is not defined  no-undef
> 
> ✖ 5 problems (5 errors, 0 warnings)

**Comment by Mik13** [comment]
This really looks like a mistake.

I will look into it in a few days.

**Comment by MadMG** [comment]
👍
